work_dir: '/home/azureuser/webserver'
registry: 'acrjego.azurecr.io'
image_tag: 'casopractico2'
web_app_image_name: 'web_app'
persistent_app_image_name: 'nginx'
acr_username: 'acrjego'
acr_userpass: 'rGqt2IRwkpT6Btf1fuBxyJfuFArh4pvhrk2t0DRnQi+ACRAhbnD1'
k8s_namespace: 'casopractico2'
localhost_work_dir: "/tmp"
aplicacion:
  definicion: "persistent_app.yaml"
  frontend:
    nombre: web-server
    replicas: 1
    recursos:
      cpu: 100m
      memoria: 128Mi
    limites:
      cpu: 250m
      memoria: 256Mi
    puerto: 80
  storage:
    pvc_name: pvc-file-csi
    pv_name: pv-file-csi
    capacity: 1Gi
    storage_class: azurefile-csi
  
